name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run create --if-present
    - run: rm -rf /var/www/site1 && mv ./build reactapp && sudo mv ./reactapp /var/www/